version: 2
jobs:
  test_dev:
    docker:
      - image: circleci/ruby:latest
    
    steps:
      - run: echo hello


workflows:
  version: 2
  dev_stage_pre-prod:
    jobs:
      - test_dev:
          filters:
            branches:
              only: dev
