
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: 
          command: |
            docker --version





#version: 2
#jobs:
#  build:
#    working_directory: ~/test
#    machine: true
#    
#    steps:
#      - run: sudo apt-get install openvpn-client
    
