version: 2
jobs:
  working_directory: ~/test
  test:
    docker:
      - image: circleci/ruby:2.1.10
    
    steps:
      - run: echo hello


workflows:
  version: 2
  dev_stage_pre-prod:
    jobs:
      - test:
          filters:
            branches:
              only: /dev-*/
