version: 2
jobs:
  build:
    working_directory: ~/test
    docker:
      - image: circleci/python:latest
      - image: circleci/mysql:latest
    
    steps:
      - run: echo "time to get started"
    
