
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install openvpn
      - run: sudo cp /usr/share/doc/openvpn/examples/sample-config-files/client.conf /etc/openvpn/
      - run: sleep 1000





#version: 2
#jobs:
#  build:
#    working_directory: ~/test
#    machine: true
#    
#    steps:
#      - run: sudo apt-get install openvpn-client
    
