version: 2
jobs:
  build:
    working_directory: ~/test
    machine: true
    
    steps:
      - run: wget http://qt.mirrors.tds.net/qt/archive/qt/5.9/5.9.3/qt-opensource-linux-x64-5.9.3.run
      - run: sudo ./qt-opensource-linux-x64-5.9.3.run
      
