defaults: &defaults
  working_directory: /tmp

version: 2
debug: true
jobs:
  build:
    <<: *defaults
    docker:
      - image: golang:alpine
    steps:
      - run: echo 'export TEST_TWO=$TEST_ONE' >> $BASH_ENV 
      - run: env

workflows:
  version: 2

  btd:
    jobs:
      - build:
          context: org-global


#version: 2
#jobs:
#  build:
#    working_directory: ~/test
#    machine: true
#    
#    steps:
#      - run: sudo apt-get install openvpn-client
    
